apiVersion: v1
kind: Service
metadata:
  name: clustache-service
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: clustache
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: clustache