apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clustache.labelApp }}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Values.clustache.labelApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.clustache.labelApp }}
    spec:
      containers:
      - name: clustache
        image: {{ .Values.clustache.image  }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.clustache.port }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: REDIS_PATH
          value: {{.Values.redis.serviceName }}
        - name: REDIS_PORT
          value: {{.Values.redis.port | quote }}