apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clustache.serviceName }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ .Values.clustache.labelApp }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.clustache.port }}
      targetPort: {{ .Values.clustache.port }}
  selector:
    app: clustache