apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
spec:
  selector:
    app:  {{ .Values.redis.serviceName }}
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  type: ClusterIP
