apiVersion: v2
name: clustache-chart
description: A Helm chart for Clustache

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: "27.3.1"

  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: "8.10.0"
