clustache:
  serviceName: clustache-service
  labelApp: clustache
  port: 8080
  image: clustache:latest

clustachemockserver:
  serviceName: clustache-mock-database-service
  labelApp: clustache-mock-database
  port: 8081
  image: clustache-mock-database:latest


grafana:
  adminPassword: admin
  service:
    type: LoadBalancer